// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TiempoBiblia.Api.Data;

#nullable disable

namespace TiempoBiblia.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714225321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TiempoBiblia.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.PaqueteProducto", b =>
                {
                    b.Property<int>("PaqueteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("PaqueteId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PaqueteProductos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsGratuito")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.ProductoRelacionado", b =>
                {
                    b.Property<int>("ProductoOrigenId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoRelacionadoId")
                        .HasColumnType("integer");

                    b.HasKey("ProductoOrigenId", "ProductoRelacionadoId");

                    b.HasIndex("ProductoRelacionadoId");

                    b.ToTable("ProductosRelacionados");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.ProductoTag", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductoTags");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.TokenDescarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorreoCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DescargasRealizadas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LimiteDescargas")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("TokensDescargas");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.PaqueteProducto", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Models.Paquete", "Paquete")
                        .WithMany("PaqueteProductos")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiempoBiblia.Api.Models.Producto", "Producto")
                        .WithMany("PaqueteProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.Producto", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.ProductoRelacionado", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Models.Producto", "ProductoOrigen")
                        .WithMany("ProductosRelacionadosOrigen")
                        .HasForeignKey("ProductoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoBiblia.Api.Models.Producto", "ProductoRelacionadoDestino")
                        .WithMany("ProductosRelacionadosDestino")
                        .HasForeignKey("ProductoRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoOrigen");

                    b.Navigation("ProductoRelacionadoDestino");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.ProductoTag", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Models.Producto", "Producto")
                        .WithMany("ProductoTags")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiempoBiblia.Api.Models.Tag", "Tag")
                        .WithMany("ProductoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.TokenDescarga", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.Paquete", b =>
                {
                    b.Navigation("PaqueteProductos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.Producto", b =>
                {
                    b.Navigation("PaqueteProductos");

                    b.Navigation("ProductoTags");

                    b.Navigation("ProductosRelacionadosDestino");

                    b.Navigation("ProductosRelacionadosOrigen");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Models.Tag", b =>
                {
                    b.Navigation("ProductoTags");
                });
#pragma warning restore 612, 618
        }
    }
}
