// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TiempoBiblia.Api.Data;

#nullable disable

namespace TiempoBiblia.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818130836_AgregarSistemaResenasv2")]
    partial class AgregarSistemaResenasv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TiempoBiblia.Api.Features.Categorias.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Paquetes.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Pedidos.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Franquicia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Pasarela")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalCobrado")
                        .HasColumnType("numeric");

                    b.Property<string>("TransaccionGatewayId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ultimos4Digitos")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Pedidos.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProductoHistorico")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitarioPagado")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoDetalles");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Productos.ImagenProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ImagenesProductos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Productos.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<bool>("EsGratuito")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Relaciones.PaqueteProducto", b =>
                {
                    b.Property<int>("PaqueteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("PaqueteId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PaqueteProductos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Relaciones.ProductoCategoriaSecundaria", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ProductoCategoriasSecundarias");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Relaciones.ProductoRelacionado", b =>
                {
                    b.Property<int>("ProductoOrigenId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoRelacionadoId")
                        .HasColumnType("integer");

                    b.HasKey("ProductoOrigenId", "ProductoRelacionadoId");

                    b.HasIndex("ProductoRelacionadoId");

                    b.ToTable("ProductosRelacionados");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Relaciones.ProductoTag", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductoTags");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Resenas.Resena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobada")
                        .HasColumnType("boolean");

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Resenas");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Tags.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TiempoBiblia.Api.shared.TokenDescarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorreoCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DescargasRealizadas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LimiteDescargas")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("TokensDescarga");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Pedidos.PedidoDetalle", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Features.Pedidos.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Productos.ImagenProducto", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Features.Productos.Producto", "Producto")
                        .WithMany("ImagenesSecundarias")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Productos.Producto", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Features.Categorias.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Relaciones.PaqueteProducto", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Features.Paquetes.Paquete", "Paquete")
                        .WithMany("PaqueteProductos")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiempoBiblia.Api.Features.Productos.Producto", "Producto")
                        .WithMany("PaqueteProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Relaciones.ProductoCategoriaSecundaria", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Features.Categorias.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiempoBiblia.Api.Features.Productos.Producto", "Producto")
                        .WithMany("CategoriasSecundarias")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Relaciones.ProductoRelacionado", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Features.Productos.Producto", "ProductoOrigen")
                        .WithMany("ProductosRelacionadosOrigen")
                        .HasForeignKey("ProductoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoBiblia.Api.Features.Productos.Producto", "ProductoRelacionadoDestino")
                        .WithMany("ProductosRelacionadosDestino")
                        .HasForeignKey("ProductoRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoOrigen");

                    b.Navigation("ProductoRelacionadoDestino");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Relaciones.ProductoTag", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Features.Productos.Producto", "Producto")
                        .WithMany("ProductoTags")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiempoBiblia.Api.Features.Tags.Tag", "Tag")
                        .WithMany("ProductoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TiempoBiblia.Api.shared.TokenDescarga", b =>
                {
                    b.HasOne("TiempoBiblia.Api.Features.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Categorias.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Paquetes.Paquete", b =>
                {
                    b.Navigation("PaqueteProductos");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Pedidos.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Productos.Producto", b =>
                {
                    b.Navigation("CategoriasSecundarias");

                    b.Navigation("ImagenesSecundarias");

                    b.Navigation("PaqueteProductos");

                    b.Navigation("ProductoTags");

                    b.Navigation("ProductosRelacionadosDestino");

                    b.Navigation("ProductosRelacionadosOrigen");
                });

            modelBuilder.Entity("TiempoBiblia.Api.Features.Tags.Tag", b =>
                {
                    b.Navigation("ProductoTags");
                });
#pragma warning restore 612, 618
        }
    }
}
